#Assets

#### Create a new asset

# @name createAsset
POST http://localhost:3000/assets
Content-Type: application/json

{
  "name": "Amazon1",
  "symbol": "A11",
  "price": "100",
  "image": "amz.jpeg"
}

### 
@assetId = {{ createAsset.response.body._id }}
@assetSymbol = {{ createAsset.response.body.symbol }}

#### Get All assets
GET http://localhost:3000/assets
Content-Type: application/json

#### Get one asset by id
GET http://localhost:3000/assets/A1
Content-Type: application/json

#### Get one asset by id created now (use the id from the response of the POST request)
GET http://localhost:3000/assets/{{assetSymbol}}
Content-Type: application/json


#Wallets

### Create a new wallet

# @name createWallet 

POST http://localhost:3000/wallets
Content-Type: application/json

### 
@walletId = {{ createWallet.response.body._id }}

#### Get All wallets
GET http://localhost:3000/wallets
Content-Type: application/json

#### Get one wallet by id
GET http://localhost:3000/wallets/665b87ae-ef28-4bbe-8c17-b892593a3feb
Content-Type: application/json

#### Get one wallet by id created now (use the id from the response of the POST request)
GET http://localhost:3000/wallets/{{walletId}}
Content-Type: application/json

#### Add asset to wallet

POST http://localhost:3000/wallets/{{walletId}}/assets
Content-Type: application/json

{
    "assetId": "{{assetId}}",
    "shares": 100
}



#ORDERS

### Create a new ORDER

# @name createOrder 

POST http://localhost:3000/orders
Content-Type: application/json

{
    "assetId": "{{assetId}}",
    "walletId": "{{walletId}}",
    "shares": 100,
    "price": 100,
    "type": "BUY"   
}

### 
@orderId = {{ createOrder.response.body._id }}


#### Get one orders by id
GET http://localhost:3000/orders/665b87ae-ef28-4bbe-8c17-b892593a3feb
Content-Type: application/json

#### Get one order by id created now (use the id from the response of the POST request)
GET http://localhost:3000/orders/{{orderId}}
Content-Type: application/json